#!/bin/bash

############################# BEGIN PBS DIRECTIVES #############################

### mail on job exit
#PBS -m e

### email address to send job updates
#PBS -M huanans@bcm.edu

### keep job output and error files in your home directory
### this overrides -e and -o options to specify error/output file locations
#PBS -k oe

### request 1 CPUs on 1 node
#PBS -l nodes=1:ppn=8

### request 64gb virtual memory TOTAL

#PBS -l vmem=64gb

### request 2 days walltime
#PBS -l walltime=48:00:00

############################## END PBS DIRECTIVES ##############################


### enable 'module' commands
source /etc/profile.d/modules.sh

### JOB EXECUTION ###

echo "job start directory: ${PBS_O_WORKDIR}"

cd /mount/durgan/EODF_result/

module load anaconda3/2019.10
source activate /project/durgan



### setup environmental variables

### make changes here
mkdir /project/durgan/EODF/humann3_output/SAMPLE_DIRECTORY
humann --input=SAMPLE_DIRECTORY/kneaddata/main/SAMPLE_DIRECTORY.fastq --search-mode=uniref90 --translated-identity-threshold=70 --thread=8 --input-format=fastq --output=/project/durgan/EODF/humann3_output/SAMPLE_DIRECTORY --diamond=/project/durgan/bin/diamond --metaphlan-option=--bowtie2db=/mount/durgan/humann_database/metaphlan_db/ --remove-temp-output 

cd /project/durgan/EODF/humann3_output/

mv SAMPLE_DIRECTORY /mount/durgan/EODF_humann3 
### ignore below here, just example commands...


