library(vegan)
metadata=read.csv('~/Box Sync/EODF_analysis/raw_data/metadata/Metadata_16s_dif.csv',row.names = 1)
asv=read.csv('~/Box Sync/EODF_analysis/intermediate_files/16s/dada2_output/asv_grouped.csv',header = T,row.names = 1)
samples = rownames(metadata)
samples = gsub('-','.',samples)
rownames(metadata)=samples
samples = intersect(samples,colnames(asv))
asv= asv[,samples]
metadata = metadata[samples,]
#asv_relab = t(na.omit(data.frame(sapply(asv,function(x) x/sum(x)),row.names = rownames(asv))))
asv = t(asv)
# asv.bc.dist=vegdist(asv, method = "bray")
# asv.bc.clust = hclust(asv.bc.dist, method = "average")
# 
# asv.bc.beta = betadisper(asv.bc.dist, metadata$Group)
# stat=adonis(asv.bc.dist~metadata$Genotype+metadata$Treatment + metadata$Genotype:metadata$Treatment, method = "bray")
# scores(asv.bc.beta)
# par(cex.lab=1.5)
# par(cex.axis=1)
# pcoa.all.fig = ordiplot(asv.bc.beta, type = "none", ylim = c(-0.4,0.4),xlim=c(-0.5,0.9),
#                         xlab = paste("PCoA 1 (", round(asv.bc.beta$eig[1]/sum(asv.bc.beta$eig)*100,2), "% explained)"), 
#                         ylab = paste("PCoA 2 (", round(asv.bc.beta$eig[2]/sum(asv.bc.beta$eig)*100,2), "% explained)"))
# points(pcoa.all.fig, "sites", pch = 19, col = "blue", select = metadata$Group == "WKY_Con")
# points(pcoa.all.fig, "sites", pch = 19, col = "purple", select = metadata$Group == "WKY_EODF")
# points(pcoa.all.fig, "sites", pch = 19, col = "red", select = metadata$Group == "SHRSP_Con")
# points(pcoa.all.fig, "sites", pch = 19, col = "green", select = metadata$Group == "SHRSP_EODF")
# #ordiellipse(asv.bc.beta, metadata$Group, conf = 0.95, label = F,col = c("red","green","blue","purple"))
# ordispider(asv.bc.beta,metadata$Group,col = c("red","green","blue","purple"))
# legend("bottomright",legend = levels(metadata$Group), col = c("red","green","blue","purple"), pch = 16)
# mtext(paste("p = ", as.character(stat$aov.tab$`Pr(>F)`[1])))
# dev.off()
# rm(stat)
WKY_sample = rownames(metadata[metadata$Genotype == "WKY",])
SHRSP_sample = rownames(metadata[metadata$Genotype == "SHRSP",])
asv.wky.bc.dist = vegdist(asv[WKY_sample,], method = "bray")
asv.wky.bc.clust = hclust(asv.wky.bc.dist, method = "average")
asv.shrsp.bc.dist = vegdist(asv[SHRSP_sample,], method = "bray")
asv.shrsp.bc.clust = hclust(asv.shrsp.bc.dist, method = "average")
#stat.wky = anosim(asv.wky.bc.dist, grouping = metadata[WKY_sample,"Group"], distance = "bray")
#stat.shrsp = anosim(asv.shrsp.bc.dist, grouping = metadata[SHRSP_sample,"Group"], distance = "bray")
stat.wky=adonis(asv.wky.bc.dist~metadata[WKY_sample,"Group"], method = "bray")
stat.shrsp=adonis(asv.shrsp.bc.dist~metadata[SHRSP_sample,"Group"], method = "bray")
asv.wky.beta = betadisper(asv.wky.bc.dist, metadata[WKY_sample,"Group"])
asv.shrsp.beta = betadisper(asv.shrsp.bc.dist, metadata[SHRSP_sample,"Group"])
pcoa.wky.fig = ordiplot(asv.wky.beta, type = "none", ylim = c(-0.3,0.3), xlim = c(-0.2,0.3),
                        xlab = paste("PCoA 1 (", round(asv.wky.beta$eig[1]/sum(asv.wky.beta$eig)*100,2), "% explained)"), 
                        ylab = paste("PCoA 2 (", round(asv.wky.beta$eig[2]/sum(asv.wky.beta$eig)*100,2), "% explained)"))
points(pcoa.wky.fig, "sites", pch = 19, col = "cyan", select = metadata[WKY_sample,"Group"] == "WKY_Con_C")
points(pcoa.wky.fig, "sites", pch = 19, col = "black", select = metadata[WKY_sample,"Group"] == "WKY_Con_G")
points(pcoa.wky.fig, "sites", pch = 19, col = "blue", select = metadata[WKY_sample,"Group"] == "WKY_Con_GF")
points(pcoa.wky.fig, "sites", pch = 19, col = "purple", select = metadata[WKY_sample,"Group"] == "WKY_EODF_GF")
points(pcoa.wky.fig, "sites", pch = 19, col = "brown", select = metadata[WKY_sample,"Group"] == "WKY_EODF_C")
points(pcoa.wky.fig, "sites", pch = 19, col = "grey", select = metadata[WKY_sample,"Group"] == "WKY_EODF_G")

#ordiellipse(asv.wky.beta, metadata[WKY_sample,"Treatment"], conf = 0.95,col = c("blue","purple"))
ordispider(asv.wky.beta,metadata[WKY_sample,"Group"], col= c("cyan","black","blue","brown","grey","purple"))
legend("bottomright",legend = levels(metadata[WKY_sample,"Group"])[7:12], col= c("cyan","black","blue","brown","grey","purple"), pch = 16)
mtext(paste("p = ", as.character(stat.wky$aov.tab$`Pr(>F)`[1])))
dev.off()

pcoa.shrsp.fig = ordiplot(asv.shrsp.beta, type = "none", ylim = c(-0.3,0.6), xlim = c(-0.2,0.5),
                          xlab = paste("PCoA 1 (", round(asv.shrsp.beta$eig[1]/sum(asv.shrsp.beta$eig)*100,2), "% explained)"), 
                          ylab = paste("PCoA 2 (", round(asv.shrsp.beta$eig[2]/sum(asv.shrsp.beta$eig)*100,2), "% explained)"))
points(pcoa.shrsp.fig, "sites", pch = 19, col = "pink", select = metadata[SHRSP_sample,"Group"] == "SHRSP_Con_C")
points(pcoa.shrsp.fig, "sites", pch = 19, col = "navy", select = metadata[SHRSP_sample,"Group"] == "SHRSP_Con_G")
points(pcoa.shrsp.fig, "sites", pch = 19, col = "red", select = metadata[SHRSP_sample,"Group"] == "SHRSP_Con_GF")
points(pcoa.shrsp.fig, "sites", pch = 19, col = "yellow3", select = metadata[SHRSP_sample,"Group"] == "SHRSP_EODF_C")
points(pcoa.shrsp.fig, "sites", pch = 19, col = "brown4", select = metadata[SHRSP_sample,"Group"] == "SHRSP_EODF_G")
points(pcoa.shrsp.fig, "sites", pch = 19, col = "green", select = metadata[SHRSP_sample,"Group"] == "SHRSP_EODF_GF")
#ordiellipse(asv.shrsp.beta, metadata[SHRSP_sample,"Treatment"], conf = 0.95,col = c("red","green"))
ordispider(asv.shrsp.beta,metadata[SHRSP_sample,"Group"], col= c("pink","navy","red","yellow3","brown4","green"))
legend("bottomright",legend = levels(metadata$Group)[1:6], col = c("pink","navy","red","yellow3","brown4","green"), pch = 16)
mtext(paste("p = ", as.character(stat.shrsp$aov.tab$`Pr(>F)`[1])))
dev.off()
rm(stat.wky, stat.shrsp)

